# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pack 150
subtitle: Scouting's values through fun and experience
email: info@pack150.org
description: "Pack 150 in Chagrin Falls, Ohio is a Cub Scout pack that believes in the Scouting program."
repository: Pack150/Pack150.github.io
baseurl: ""
url: "http://Pack150.org"
safe: true
incremental: false
timezone: America/New_York
encoding: utf-8

gems:
  - jekyll-redirect-from
  - jekyll-paginate

permalink: pretty
paginate: 10
paginate_path: "/news/page:num/"

collections:
  - home_page

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sidebar: false
      author: "Akela"
      layout: "post"
