# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cub Scout Pack 379
subtitle: Woodland West Church of Christ / Arlington, TX
email: info@pack379.org
description: "Pack 379 in Arlington, TX"
repository: pack379/pack379.github.io
baseurl: ""
url: "http://www.pack379.org"
safe: true
incremental: false
timezone: America/Chicago
encoding: utf-8

gems:
  - jekyll-redirect-from
  - jekyll-paginate

permalink: pretty
paginate: 10
paginate_path: "/news/page:num/"

collections:
  - home_page

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sidebar: false
      author: "Akela"
      layout: "post"
