### GENERAL SETTINGS ###

# Site settings
title: Pack 150
description: "Pack 150 in Chagrin Falls, Ohio is a Cub Scout pack that believes in the Scouting program."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: ""
url: "http://Pack150.org"
safe: true
timezone: America/New_York
encoding: utf-8

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Pack 150
    - The Federated Church
    - 76 Bell Street
    - Chagrin Falls, OH 44022
email: info@pack150.org
tel: (440) 247-6490


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Thaddeus Quintin
    position: Cubmaster, Den Leader
    text: Eagle Scout and Scouter for life.
    img: Thaddeus.jpg
    social:
      - title: envelope #use for email address
        url: mailto:cubmaster@pack150.org
      - title: twitter
        url: http://twitter.com/quiddle
  - name: Dan Angelino
    position: Den Leader, Assistant Cubmaster
    text: Keeping everyone energized
    img: Dan.jpg
    social:
      - title: envelope #use for email address
        url: mailto:dangelino@zook.cc

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We teach the values of Scouting through fun and experience."
